# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(624, 560)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_A = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_A.setGeometry(QtCore.QRect(180, 150, 75, 23))
        self.pushButton_A.setObjectName("pushButton_A")
        self.progressBar_B = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar_B.setGeometry(QtCore.QRect(190, 320, 191, 31))
        self.progressBar_B.setProperty("value", 0)
        self.progressBar_B.setObjectName("progressBar_B")
        self.pushButton_B = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_B.setGeometry(QtCore.QRect(320, 150, 75, 23))
        self.pushButton_B.setObjectName("pushButton_B")
        self.progressBar_A = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar_A.setGeometry(QtCore.QRect(190, 260, 191, 31))
        self.progressBar_A.setProperty("value", 50)
        self.progressBar_A.setObjectName("progressBar_A")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 624, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_A.setText(_translate("MainWindow", "ButtonA"))
        self.pushButton_B.setText(_translate("MainWindow", "ButtonB"))
