# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test_main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.pushButton_A = QtWidgets.QPushButton(Dialog)
        self.pushButton_A.setGeometry(QtCore.QRect(80, 30, 75, 23))
        self.pushButton_A.setObjectName("pushButton_A")
        self.pushButton_B = QtWidgets.QPushButton(Dialog)
        self.pushButton_B.setGeometry(QtCore.QRect(220, 30, 75, 23))
        self.pushButton_B.setObjectName("pushButton_B")
        self.progressBar = QtWidgets.QProgressBar(Dialog)
        self.progressBar.setGeometry(QtCore.QRect(150, 230, 118, 23))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton_A.setText(_translate("Dialog", "ButtonA"))
        self.pushButton_B.setText(_translate("Dialog", "ButtonB"))
